# Generated by Django 5.0.6 on 2026-05-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(max_length=5000, null=True)),
                ('identifier', models.IntegerField(null=True)),
                ('annotation_type', models.IntegerField(null=True)),
                ('type_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fields', models.TextField()),
                ('show_in_filter', models.CharField(max_length=10)),
                ('show_in_table', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'annotation_type',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'complex',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=100, null=True)),
                ('naming_convention', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'identifier',
            },
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taxonomy_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organism',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('protein_name', models.CharField(max_length=200, null=True)),
                ('uniprot_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('ensembl_id', models.CharField(max_length=100, null=True)),
                ('entrez_id', models.CharField(max_length=100, null=True)),
                ('sequence', models.TextField(null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('number_of_interactions_in_database', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='proteins.protein')),
            ],
            options={
                'db_table': 'external_link',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_position', models.CharField(max_length=100, null=True)),
                ('end_position', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('sequence', models.CharField(max_length=1000, null=True)),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='proteins.protein')),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='ComplexProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.ForeignKey(db_column='complex_id', on_delete=django.db.models.deletion.CASCADE, related_name='complex_proteins', to='proteins.complex')),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='complex_proteins', to='proteins.protein')),
            ],
            options={
                'db_table': 'complex_protein',
            },
        ),
        migrations.CreateModel(
            name='AnnotationProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(db_column='annotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_proteins', to='proteins.annotation')),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotation_proteins', to='proteins.protein')),
            ],
            options={
                'db_table': 'annotation_protein',
            },
        ),
        migrations.CreateModel(
            name='ProteinIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.ForeignKey(db_column='identifier_id', on_delete=django.db.models.deletion.CASCADE, related_name='protein_identifiers', to='proteins.identifier')),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='protein_identifiers', to='proteins.protein')),
            ],
            options={
                'db_table': 'protein_identifier',
            },
        ),
        migrations.CreateModel(
            name='ProteinIsoform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoform', models.ForeignKey(db_column='isoform_id', on_delete=django.db.models.deletion.CASCADE, related_name='isoform_of_links', to='proteins.protein')),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='isoform_links', to='proteins.protein')),
            ],
            options={
                'db_table': 'protein_isoform',
            },
        ),
        migrations.CreateModel(
            name='ProteinOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.ForeignKey(db_column='organism_id', on_delete=django.db.models.deletion.CASCADE, related_name='protein_organisms', to='proteins.organism')),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='protein_organisms', to='proteins.protein')),
            ],
            options={
                'db_table': 'protein_organism',
            },
        ),
    ]
