# Generated by Django 5.0.6 on 2026-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="identifier",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
