# Generated by Django 5.0.6 on 2026-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0002_fix_annotation_identifier_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationtype",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="annotationtype",
            name="fields",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="annotationtype",
            name="show_in_filter",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtype",
            name="show_in_table",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
