# Generated by Django 5.0.6 on 2026-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0003_fix_annotation_type_nullable"),
    ]

    operations = [
        # Functional index on UPPER(identifier) — Django's iexact generates
        # WHERE UPPER(identifier) = UPPER(val), which a plain btree can't use.
        migrations.RunSQL(
            sql="""
                CREATE INDEX identifier_upper_idx
                ON identifier (UPPER(identifier));
            """,
            reverse_sql="DROP INDEX IF EXISTS identifier_upper_idx;",
        ),
    ]
