# Generated by Django 5.0.6 on 2026-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0005_organism_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organism",
            name="taxonomy_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
