# Generated by Django 5.0.6 on 2026-05-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_title', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('version', models.CharField(max_length=200, null=True)),
                ('home_page', models.TextField(null=True)),
                ('mission_title', models.TextField(null=True)),
                ('mission_text', models.TextField(null=True)),
                ('method_title', models.TextField(null=True)),
                ('method_text', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('faq', models.TextField(null=True)),
                ('download', models.TextField(null=True)),
                ('contact', models.TextField(null=True)),
                ('show_downloads', models.BooleanField(default=False)),
                ('show_download_all', models.BooleanField(default=False)),
                ('footer', models.TextField(null=True)),
                ('main_color_scheme', models.CharField(max_length=10, null=True)),
                ('header_color_scheme', models.CharField(max_length=10, null=True)),
                ('logo_color_scheme', models.CharField(max_length=10, null=True)),
                ('button_color_scheme', models.CharField(max_length=10, null=True)),
                ('example_1', models.CharField(max_length=100, null=True)),
                ('example_2', models.CharField(max_length=100, null=True)),
                ('example_3', models.CharField(max_length=100, null=True)),
                ('query_node_color', models.CharField(max_length=20, null=True)),
                ('interactor_node_color', models.CharField(max_length=20, null=True)),
                ('published_edge_color', models.CharField(max_length=20, null=True)),
                ('validated_edge_color', models.CharField(max_length=20, null=True)),
                ('verified_edge_color', models.CharField(max_length=20, null=True)),
                ('literature_edge_color', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'admin settings',
                'db_table': 'admin_settings',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(null=True)),
                ('show', models.BooleanField(default=True)),
                ('show_on_home_page', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
