# Generated by Django 5.0.6 on 2026-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_adminsettings_nav_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsettings",
            name="example_1_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="example_2_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="example_3_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="adminsettings",
            name="example_1",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="adminsettings",
            name="example_2",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="adminsettings",
            name="example_3",
            field=models.TextField(null=True),
        ),
    ]
