# Generated by Django 5.0.6 on 2026-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_adminsettings_example_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("locale", models.CharField(default="en", max_length=10)),
                ("value", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "site text",
                "db_table": "site_text",
                "indexes": [
                    models.Index(fields=["locale"], name="site_text_locale_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sitetext",
            constraint=models.UniqueConstraint(
                fields=("key", "locale"), name="site_text_key_locale_uniq"
            ),
        ),
    ]
