# Generated by Django 5.0.6 on 2026-08-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_home_prose_to_site_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsettings",
            name="show_subcellular_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="adminsettings",
            name="show_tissue_expression",
            field=models.BooleanField(default=True),
        ),
    ]
