# Generated by Django 5.0.6 on 2026-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_adminsettings_show_subcellular_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsettings",
            name="horizontal_filter_bar",
            field=models.BooleanField(default=False),
        ),
    ]
