# Generated by Django 5.0.6 on 2026-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_adminsettings_horizontal_filter_bar"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsettings",
            name="nav_style_overrides",
            field=models.TextField(blank=True, null=True),
        ),
    ]
