# Generated by Django 5.0.6 on 2026-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        # Index on removed — every search filters WHERE removed='0'
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(fields=["removed"], name="interaction_removed_idx"),
        ),
        # Composite (interactor_A, interactor_B) — covers the main search join:
        # WHERE interactor_A_id IN (...) AND interactor_B_id IN (...)
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["interactor_A", "interactor_B"],
                name="interaction_a_b_idx",
            ),
        ),
        # Reverse composite — covers B-side queries in query_interactor mode
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["interactor_B", "interactor_A"],
                name="interaction_b_a_idx",
            ),
        ),
    ]
