# Generated by Django 5.0.6 on 2026-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_remove_interaction_interaction_removed_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionnetwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
