# Generated by Django 5.0.6 on 2026-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_interactionnetwork_created_at"),
        ("proteins", "0004_add_search_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(fields=["removed"], name="interaction_removed_idx"),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["interactor_A", "interactor_B"], name="interaction_a_b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["interactor_B", "interactor_A"], name="interaction_b_a_idx"
            ),
        ),
    ]
