# Generated by Django 5.0.6 on 2026-08-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_restore_search_indexes"),
        ("proteins", "0006_organism_taxonomy_id_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("A", "interactor A"), ("B", "interactor B")],
                        max_length=1,
                    ),
                ),
                (
                    "biological_role",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "experimental_role",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "interactor_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "identification_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "biological_effect",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("features", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "stoichiometry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        db_column="interaction_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="interactions.interaction",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        db_column="protein_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="proteins.protein",
                    ),
                ),
            ],
            options={
                "db_table": "interaction_participant",
                "indexes": [
                    models.Index(
                        fields=["protein", "experimental_role"],
                        name="participant_role_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="interactionparticipant",
            constraint=models.UniqueConstraint(
                fields=("interaction", "side"), name="one_participant_per_side"
            ),
        ),
    ]
