# Generated by Django 5.0.6 on 2026-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_interactionparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="negative",
            field=models.BooleanField(default=False),
        ),
    ]
