# Generated by Django 5.0.6 on 2026-08-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0007_interaction_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="interaction_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
