# Generated by Django 5.0.6 on 2026-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="security_questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
