# Generated by Django 5.0.6 on 2026-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_security_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="orcid_id",
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
    ]
