# Generated by Django 5.0.6 on 2026-08-16 03:51
#
# 0003 added orcid_id and was already applied to the deployed database, so the
# column is dropped here rather than by editing 0003 out of existence.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_orcid_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="orcid_id",
        ),
    ]
