# Generated by Django 5.0.6 on 2026-08-27 09:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_user_affiliation_user_avatar_user_bio_user_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discoverable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="user_email_unique_nonblank",
            ),
        ),
    ]
